#############################################################################
# Makefile for building: Launchy
# Generated by qmake (2.01a) (Qt 4.4.2) on: Sun Sep 21 12:45:23 2008
# Project:  Launchy.pro
# Template: subdirs
# Command: c:\qt\4.4.2\bin\qmake -win32 -o Makefile Launchy.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qt\4.4.2\bin\qmake
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-src \
		sub-plugins-calcy \
		sub-plugins-gcalc \
		sub-plugins-runner \
		sub-plugins-weby \
		sub-platforms-win32

src\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) src.pro -win32 -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) src.pro -win32 -o $(MAKEFILE)
sub-src: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
plugins\calcy\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) plugins\calcy\ $(MKDIR) plugins\calcy\ 
	cd plugins\calcy\ && $(QMAKE) calcy.pro -win32 -o $(MAKEFILE)
sub-plugins-calcy-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugins\calcy\ $(MKDIR) plugins\calcy\ 
	cd plugins\calcy\ && $(QMAKE) calcy.pro -win32 -o $(MAKEFILE)
sub-plugins-calcy: plugins\calcy\$(MAKEFILE) FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE)
sub-plugins-calcy-make_default-ordered: plugins\calcy\$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-calcy-make_default: plugins\calcy\$(MAKEFILE) FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-calcy-make_first-ordered: plugins\calcy\$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-calcy-make_first: plugins\calcy\$(MAKEFILE) FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-calcy-all-ordered: plugins\calcy\$(MAKEFILE) sub-src-all-ordered  FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-calcy-all: plugins\calcy\$(MAKEFILE) FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-calcy-clean-ordered: plugins\calcy\$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-calcy-clean: plugins\calcy\$(MAKEFILE) FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-calcy-distclean-ordered: plugins\calcy\$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-calcy-distclean: plugins\calcy\$(MAKEFILE) FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-calcy-install_subtargets-ordered: plugins\calcy\$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-calcy-install_subtargets: plugins\calcy\$(MAKEFILE) FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-calcy-uninstall_subtargets-ordered: plugins\calcy\$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-plugins-calcy-uninstall_subtargets: plugins\calcy\$(MAKEFILE) FORCE
	cd plugins\calcy\ && $(MAKE) -f $(MAKEFILE) uninstall
plugins\gcalc\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) plugins\gcalc\ $(MKDIR) plugins\gcalc\ 
	cd plugins\gcalc\ && $(QMAKE) gcalc.pro -win32 -o $(MAKEFILE)
sub-plugins-gcalc-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugins\gcalc\ $(MKDIR) plugins\gcalc\ 
	cd plugins\gcalc\ && $(QMAKE) gcalc.pro -win32 -o $(MAKEFILE)
sub-plugins-gcalc: plugins\gcalc\$(MAKEFILE) FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE)
sub-plugins-gcalc-make_default-ordered: plugins\gcalc\$(MAKEFILE) sub-plugins-calcy-make_default-ordered  FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-gcalc-make_default: plugins\gcalc\$(MAKEFILE) FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-gcalc-make_first-ordered: plugins\gcalc\$(MAKEFILE) sub-plugins-calcy-make_first-ordered  FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-gcalc-make_first: plugins\gcalc\$(MAKEFILE) FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-gcalc-all-ordered: plugins\gcalc\$(MAKEFILE) sub-plugins-calcy-all-ordered  FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-gcalc-all: plugins\gcalc\$(MAKEFILE) FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-gcalc-clean-ordered: plugins\gcalc\$(MAKEFILE) sub-plugins-calcy-clean-ordered  FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-gcalc-clean: plugins\gcalc\$(MAKEFILE) FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-gcalc-distclean-ordered: plugins\gcalc\$(MAKEFILE) sub-plugins-calcy-distclean-ordered  FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-gcalc-distclean: plugins\gcalc\$(MAKEFILE) FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-gcalc-install_subtargets-ordered: plugins\gcalc\$(MAKEFILE) sub-plugins-calcy-install_subtargets-ordered  FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-gcalc-install_subtargets: plugins\gcalc\$(MAKEFILE) FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-gcalc-uninstall_subtargets-ordered: plugins\gcalc\$(MAKEFILE) sub-plugins-calcy-uninstall_subtargets-ordered  FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-plugins-gcalc-uninstall_subtargets: plugins\gcalc\$(MAKEFILE) FORCE
	cd plugins\gcalc\ && $(MAKE) -f $(MAKEFILE) uninstall
plugins\runner\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) plugins\runner\ $(MKDIR) plugins\runner\ 
	cd plugins\runner\ && $(QMAKE) runner.pro -win32 -o $(MAKEFILE)
sub-plugins-runner-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugins\runner\ $(MKDIR) plugins\runner\ 
	cd plugins\runner\ && $(QMAKE) runner.pro -win32 -o $(MAKEFILE)
sub-plugins-runner: plugins\runner\$(MAKEFILE) FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE)
sub-plugins-runner-make_default-ordered: plugins\runner\$(MAKEFILE) sub-plugins-gcalc-make_default-ordered  FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-runner-make_default: plugins\runner\$(MAKEFILE) FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-runner-make_first-ordered: plugins\runner\$(MAKEFILE) sub-plugins-gcalc-make_first-ordered  FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-runner-make_first: plugins\runner\$(MAKEFILE) FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-runner-all-ordered: plugins\runner\$(MAKEFILE) sub-plugins-gcalc-all-ordered  FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-runner-all: plugins\runner\$(MAKEFILE) FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-runner-clean-ordered: plugins\runner\$(MAKEFILE) sub-plugins-gcalc-clean-ordered  FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-runner-clean: plugins\runner\$(MAKEFILE) FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-runner-distclean-ordered: plugins\runner\$(MAKEFILE) sub-plugins-gcalc-distclean-ordered  FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-runner-distclean: plugins\runner\$(MAKEFILE) FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-runner-install_subtargets-ordered: plugins\runner\$(MAKEFILE) sub-plugins-gcalc-install_subtargets-ordered  FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-runner-install_subtargets: plugins\runner\$(MAKEFILE) FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-runner-uninstall_subtargets-ordered: plugins\runner\$(MAKEFILE) sub-plugins-gcalc-uninstall_subtargets-ordered  FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-plugins-runner-uninstall_subtargets: plugins\runner\$(MAKEFILE) FORCE
	cd plugins\runner\ && $(MAKE) -f $(MAKEFILE) uninstall
plugins\weby\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) plugins\weby\ $(MKDIR) plugins\weby\ 
	cd plugins\weby\ && $(QMAKE) weby.pro -win32 -o $(MAKEFILE)
sub-plugins-weby-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugins\weby\ $(MKDIR) plugins\weby\ 
	cd plugins\weby\ && $(QMAKE) weby.pro -win32 -o $(MAKEFILE)
sub-plugins-weby: plugins\weby\$(MAKEFILE) FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE)
sub-plugins-weby-make_default-ordered: plugins\weby\$(MAKEFILE) sub-plugins-runner-make_default-ordered  FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-weby-make_default: plugins\weby\$(MAKEFILE) FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-weby-make_first-ordered: plugins\weby\$(MAKEFILE) sub-plugins-runner-make_first-ordered  FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-weby-make_first: plugins\weby\$(MAKEFILE) FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-weby-all-ordered: plugins\weby\$(MAKEFILE) sub-plugins-runner-all-ordered  FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-weby-all: plugins\weby\$(MAKEFILE) FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-weby-clean-ordered: plugins\weby\$(MAKEFILE) sub-plugins-runner-clean-ordered  FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-weby-clean: plugins\weby\$(MAKEFILE) FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-weby-distclean-ordered: plugins\weby\$(MAKEFILE) sub-plugins-runner-distclean-ordered  FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-weby-distclean: plugins\weby\$(MAKEFILE) FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-weby-install_subtargets-ordered: plugins\weby\$(MAKEFILE) sub-plugins-runner-install_subtargets-ordered  FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-weby-install_subtargets: plugins\weby\$(MAKEFILE) FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-weby-uninstall_subtargets-ordered: plugins\weby\$(MAKEFILE) sub-plugins-runner-uninstall_subtargets-ordered  FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-plugins-weby-uninstall_subtargets: plugins\weby\$(MAKEFILE) FORCE
	cd plugins\weby\ && $(MAKE) -f $(MAKEFILE) uninstall
platforms\win32\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) platforms\win32\ $(MKDIR) platforms\win32\ 
	cd platforms\win32\ && $(QMAKE) win32.pro -win32 -o $(MAKEFILE)
sub-platforms-win32-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) platforms\win32\ $(MKDIR) platforms\win32\ 
	cd platforms\win32\ && $(QMAKE) win32.pro -win32 -o $(MAKEFILE)
sub-platforms-win32: platforms\win32\$(MAKEFILE) FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE)
sub-platforms-win32-make_default-ordered: platforms\win32\$(MAKEFILE) sub-plugins-weby-make_default-ordered  FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) 
sub-platforms-win32-make_default: platforms\win32\$(MAKEFILE) FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) 
sub-platforms-win32-make_first-ordered: platforms\win32\$(MAKEFILE) sub-plugins-weby-make_first-ordered  FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) first
sub-platforms-win32-make_first: platforms\win32\$(MAKEFILE) FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) first
sub-platforms-win32-all-ordered: platforms\win32\$(MAKEFILE) sub-plugins-weby-all-ordered  FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) all
sub-platforms-win32-all: platforms\win32\$(MAKEFILE) FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) all
sub-platforms-win32-clean-ordered: platforms\win32\$(MAKEFILE) sub-plugins-weby-clean-ordered  FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) clean
sub-platforms-win32-clean: platforms\win32\$(MAKEFILE) FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) clean
sub-platforms-win32-distclean-ordered: platforms\win32\$(MAKEFILE) sub-plugins-weby-distclean-ordered  FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) distclean
sub-platforms-win32-distclean: platforms\win32\$(MAKEFILE) FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) distclean
sub-platforms-win32-install_subtargets-ordered: platforms\win32\$(MAKEFILE) sub-plugins-weby-install_subtargets-ordered  FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) install
sub-platforms-win32-install_subtargets: platforms\win32\$(MAKEFILE) FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) install
sub-platforms-win32-uninstall_subtargets-ordered: platforms\win32\$(MAKEFILE) sub-plugins-weby-uninstall_subtargets-ordered  FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-platforms-win32-uninstall_subtargets: platforms\win32\$(MAKEFILE) FORCE
	cd platforms\win32\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: Launchy.pro  ..\..\QT\4.4.2\mkspecs\default\qmake.conf ..\..\QT\4.4.2\mkspecs\qconfig.pri \
		..\..\QT\4.4.2\mkspecs\features\qt_functions.prf \
		..\..\QT\4.4.2\mkspecs\features\qt_config.prf \
		..\..\QT\4.4.2\mkspecs\features\exclusive_builds.prf \
		..\..\QT\4.4.2\mkspecs\features\default_pre.prf \
		..\..\QT\4.4.2\mkspecs\features\win32\default_pre.prf \
		..\..\QT\4.4.2\mkspecs\features\debug.prf \
		..\..\QT\4.4.2\mkspecs\features\debug_and_release.prf \
		..\..\QT\4.4.2\mkspecs\features\default_post.prf \
		..\..\QT\4.4.2\mkspecs\features\win32\rtti.prf \
		..\..\QT\4.4.2\mkspecs\features\win32\exceptions.prf \
		..\..\QT\4.4.2\mkspecs\features\shared.prf \
		..\..\QT\4.4.2\mkspecs\features\win32\embed_manifest_exe.prf \
		..\..\QT\4.4.2\mkspecs\features\win32\embed_manifest_dll.prf \
		..\..\QT\4.4.2\mkspecs\features\warn_on.prf \
		..\..\QT\4.4.2\mkspecs\features\qt.prf \
		..\..\QT\4.4.2\mkspecs\features\win32\thread.prf \
		..\..\QT\4.4.2\mkspecs\features\moc.prf \
		..\..\QT\4.4.2\mkspecs\features\win32\windows.prf \
		..\..\QT\4.4.2\mkspecs\features\win32\stl_off.prf \
		..\..\QT\4.4.2\mkspecs\features\resources.prf \
		..\..\QT\4.4.2\mkspecs\features\uic.prf \
		..\..\QT\4.4.2\mkspecs\features\yacc.prf \
		..\..\QT\4.4.2\mkspecs\features\lex.prf
	$(QMAKE) -win32 -o Makefile Launchy.pro
..\..\QT\4.4.2\mkspecs\qconfig.pri:
..\..\QT\4.4.2\mkspecs\features\qt_functions.prf:
..\..\QT\4.4.2\mkspecs\features\qt_config.prf:
..\..\QT\4.4.2\mkspecs\features\exclusive_builds.prf:
..\..\QT\4.4.2\mkspecs\features\default_pre.prf:
..\..\QT\4.4.2\mkspecs\features\win32\default_pre.prf:
..\..\QT\4.4.2\mkspecs\features\debug.prf:
..\..\QT\4.4.2\mkspecs\features\debug_and_release.prf:
..\..\QT\4.4.2\mkspecs\features\default_post.prf:
..\..\QT\4.4.2\mkspecs\features\win32\rtti.prf:
..\..\QT\4.4.2\mkspecs\features\win32\exceptions.prf:
..\..\QT\4.4.2\mkspecs\features\shared.prf:
..\..\QT\4.4.2\mkspecs\features\win32\embed_manifest_exe.prf:
..\..\QT\4.4.2\mkspecs\features\win32\embed_manifest_dll.prf:
..\..\QT\4.4.2\mkspecs\features\warn_on.prf:
..\..\QT\4.4.2\mkspecs\features\qt.prf:
..\..\QT\4.4.2\mkspecs\features\win32\thread.prf:
..\..\QT\4.4.2\mkspecs\features\moc.prf:
..\..\QT\4.4.2\mkspecs\features\win32\windows.prf:
..\..\QT\4.4.2\mkspecs\features\win32\stl_off.prf:
..\..\QT\4.4.2\mkspecs\features\resources.prf:
..\..\QT\4.4.2\mkspecs\features\uic.prf:
..\..\QT\4.4.2\mkspecs\features\yacc.prf:
..\..\QT\4.4.2\mkspecs\features\lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -win32 -o Makefile Launchy.pro

qmake_all: sub-src-qmake_all sub-plugins-calcy-qmake_all sub-plugins-gcalc-qmake_all sub-plugins-runner-qmake_all sub-plugins-weby-qmake_all sub-platforms-win32-qmake_all FORCE

make_default: sub-src-make_default-ordered sub-plugins-calcy-make_default-ordered sub-plugins-gcalc-make_default-ordered sub-plugins-runner-make_default-ordered sub-plugins-weby-make_default-ordered sub-platforms-win32-make_default-ordered FORCE
make_first: sub-src-make_first-ordered sub-plugins-calcy-make_first-ordered sub-plugins-gcalc-make_first-ordered sub-plugins-runner-make_first-ordered sub-plugins-weby-make_first-ordered sub-platforms-win32-make_first-ordered FORCE
all: sub-src-all-ordered sub-plugins-calcy-all-ordered sub-plugins-gcalc-all-ordered sub-plugins-runner-all-ordered sub-plugins-weby-all-ordered sub-platforms-win32-all-ordered FORCE
clean: sub-src-clean-ordered sub-plugins-calcy-clean-ordered sub-plugins-gcalc-clean-ordered sub-plugins-runner-clean-ordered sub-plugins-weby-clean-ordered sub-platforms-win32-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-plugins-calcy-distclean-ordered sub-plugins-gcalc-distclean-ordered sub-plugins-runner-distclean-ordered sub-plugins-weby-distclean-ordered sub-platforms-win32-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-plugins-calcy-install_subtargets-ordered sub-plugins-gcalc-install_subtargets-ordered sub-plugins-runner-install_subtargets-ordered sub-plugins-weby-install_subtargets-ordered sub-platforms-win32-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-plugins-calcy-uninstall_subtargets-ordered sub-plugins-gcalc-uninstall_subtargets-ordered sub-plugins-runner-uninstall_subtargets-ordered sub-plugins-weby-uninstall_subtargets-ordered sub-platforms-win32-uninstall_subtargets-ordered FORCE

sub-src-sub_Debug_ordered: src\\$(MAKEFILE)
	cd src\ && $(MAKE) debug
sub-plugins-calcy-sub_Debug_ordered: plugins\calcy\\$(MAKEFILE) sub-src-sub_Debug_ordered 
	cd plugins\calcy\ && $(MAKE) debug
sub-plugins-gcalc-sub_Debug_ordered: plugins\gcalc\\$(MAKEFILE) sub-plugins-calcy-sub_Debug_ordered 
	cd plugins\gcalc\ && $(MAKE) debug
sub-plugins-runner-sub_Debug_ordered: plugins\runner\\$(MAKEFILE) sub-plugins-gcalc-sub_Debug_ordered 
	cd plugins\runner\ && $(MAKE) debug
sub-plugins-weby-sub_Debug_ordered: plugins\weby\\$(MAKEFILE) sub-plugins-runner-sub_Debug_ordered 
	cd plugins\weby\ && $(MAKE) debug
sub-platforms-win32-sub_Debug_ordered: platforms\win32\\$(MAKEFILE) sub-plugins-weby-sub_Debug_ordered 
	cd platforms\win32\ && $(MAKE) debug
debug: sub-src-sub_Debug_ordered sub-plugins-calcy-sub_Debug_ordered sub-plugins-gcalc-sub_Debug_ordered sub-plugins-runner-sub_Debug_ordered sub-plugins-weby-sub_Debug_ordered sub-platforms-win32-sub_Debug_ordered

sub-src-sub_Release_ordered: src\\$(MAKEFILE)
	cd src\ && $(MAKE) release
sub-plugins-calcy-sub_Release_ordered: plugins\calcy\\$(MAKEFILE) sub-src-sub_Release_ordered 
	cd plugins\calcy\ && $(MAKE) release
sub-plugins-gcalc-sub_Release_ordered: plugins\gcalc\\$(MAKEFILE) sub-plugins-calcy-sub_Release_ordered 
	cd plugins\gcalc\ && $(MAKE) release
sub-plugins-runner-sub_Release_ordered: plugins\runner\\$(MAKEFILE) sub-plugins-gcalc-sub_Release_ordered 
	cd plugins\runner\ && $(MAKE) release
sub-plugins-weby-sub_Release_ordered: plugins\weby\\$(MAKEFILE) sub-plugins-runner-sub_Release_ordered 
	cd plugins\weby\ && $(MAKE) release
sub-platforms-win32-sub_Release_ordered: platforms\win32\\$(MAKEFILE) sub-plugins-weby-sub_Release_ordered 
	cd platforms\win32\ && $(MAKE) release
release: sub-src-sub_Release_ordered sub-plugins-calcy-sub_Release_ordered sub-plugins-gcalc-sub_Release_ordered sub-plugins-runner-sub_Release_ordered sub-plugins-weby-sub_Release_ordered sub-platforms-win32-sub_Release_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

